### Successful test: check response status is 200
GET {{baseUrl}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Check response status and content-type
GET {{baseUrl}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Response content-type is json", function() {
  const type = response.contentType.mimeType;
  client.assert(type === "text/html", `Expected 'text/html' but received '${type}'`);
});
%}

### Successful test: check response status is 200
POST {{apiBaseUrl}}\signup

{
  "username": "username",
  "password": "password",

}


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

