name: Automated tests

on:
  workflow_dispatch:
    inputs:
      run:
        description: "Run tests"
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: set up python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run Flake8
        run: flake8 .

  test:
    needs: flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: set up python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12.0"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install
      - name: Run tests
        run: |
          pytest

  allure:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install allure-pytest
      - name: Install Allure commandline
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && 
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
      - name: Generate Allure report
        run: allure generate allure_results --clean
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure_results
      - name: Deploy report to Github Pages
        uses: actions/deploy-pages@v1.2.9
        with:
          target-folder: allure_results









