name: Automated tests

on:
  workflow_dispatch:
    inputs:
      run:
        description: "Run tests"
        required: false
      parallel:
        description: "Run tests in parallel"
        required: false
        default: 'false'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  Flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: set up python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run Flake8
        run: flake8 .

  Test:
    needs: Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: set up python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12.0"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install
      
      - name: Run tests with coverage
        run: |
          if [ "${{ github.event.inputs.parallel }}" = "true" ]
          then
            pytest --cov=. --base-url https://demoblaze.com/ --numprocesses auto --alluredir=allure-results
          else
            pytest --cov=. --base-url https://demoblaze.com/ --alluredir=allure-results
          fi

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: ZhikharevAl/db_web_test_automation

  allure-report:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v2


      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACTIONS }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  telegram:
    name: Send message to Telegram
    runs-on: ubuntu-latest
    needs: [Test, allure-report]
    steps:
      - name: Send success message to Telegram
        if: success()
        run: |
          curl --location 'https://api.telegram.org/bot${{ secrets.TG }}/sendMessage' \
          --header 'Content-Type: application/json' \
          --data '{
              "chat_id": 360370142,
              "text": "🎉 Tests passed successfully. Report: https://zhikhareval.github.io/db_web_test_automation"
          }'
      - name: Send failure message to Telegram
        if: failure()
        run: |
          curl --location 'https://api.telegram.org/bot${{ secrets.TG }}/sendMessage' \
          --header 'Content-Type: application/json' \
          --data '{
              "chat_id": 360370142,
              "text": "😞 Tests failed. Report: https://zhikhareval.github.io/db_web_test_automation"
          }'
