name: Automated tests

on:
  workflow_dispatch:
    inputs:
      run:
        description: "Run tests"
        required: false
      parallel:
        description: "Run tests in parallel"
        required: false
        default: 'false'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Ruff-lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: set up python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.12.4"
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Check code formatting with Ruff
        run: ruff check

  Test:
    needs: [ Ruff-lint-check ]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: set up python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12.4"
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov openai
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: Run tests with coverage
        id: run_tests
        run: |
          if [ "${{ github.event.inputs.parallel }}" = "true" ]
          then
            pytest --cov=. --base-url https://demoblaze.com/ --numprocesses auto --alluredir=allure-results 2>&1 | tee pytest.log
          else
            pytest --cov=. --base-url https://demoblaze.com/ --alluredir=allure-results 2>&1 | tee pytest.log
          fi
      - name: Analyze logs with ChatGPT
        if: failure()
        run: |
          python analyze_logs.py "$(cat pytest.log)" > chatgpt_analysis.txt
          cat chatgpt_analysis.txt
      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
      - name: Get Allure history
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ZhikharevAl/db_web_test_automation
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACTIONS }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  telegram:
    name: Send message to Telegram
    runs-on: ubuntu-latest
    needs: [ Ruff-lint-check, Test ]
    steps:
      - name: Send success message to Telegram
        if: success()
        run: |
          curl --location 'https://api.telegram.org/bot${{ secrets.TG }}/sendMessage' \
          --header 'Content-Type: application/json' \
          --data '{
              "chat_id": 360370142,
              "text": "🎉 Tests passed successfully. Report: https://zhikhareval.github.io/db_web_test_automation"
          }'
      - name: Send failure message to Telegram
        if: failure()
        run: |
          curl --location 'https://api.telegram.org/bot${{ secrets.TG }}/sendMessage' \
          --header 'Content-Type: application/json' \
          --data '{
              "chat_id": 360370142,
              "text": "😞 Tests failed. Report: https://zhikhareval.github.io/db_web_test_automation"
          }'
