name: Automated tests

on:
  workflow_dispatch:
    inputs:
      run:
        description: "Run tests"
        required: false

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: set up python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run Flake8
        run: flake8 .

  test:
    needs: flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: set up python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12.0"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install
      - name: Run tests
        run: |
          pytest

  allure:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install allure-pytest
      - name: Install Allure commandline
        run: |
          curl -o allure-2.8.1.tgz -Ls https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.8.1/allure-2.8.1.tgz
          sudo tar -zxvf allure-2.8.1.tgz -C /opt/
          echo "PATH=$PATH:/opt/allure-2.8.1/bin/" >> $GITHUB_ENV
      - name: Generate Allure report
        run: allure generate allure_results --clean
      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_DEPUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-report







